import { Platform, StyleSheet } from 'react-native';
import { C, BOOK_COVER_ASPECT_RATIO } from './theme';

const AI_RADIUS = {
  sheet: 24,
  surface: 16,
  field: 18,
  compact: 12,
  image: 11,
} as const;

const APPEARANCE_RADIUS = {
  card: 14,
  option: 10,
  swatch: 8,
} as const;

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: C.ink },
  splash: { flex: 1, backgroundColor: C.ink, alignItems: 'center', justifyContent: 'center' },
  mark: { width: 66, height: 78, borderWidth: 1, borderColor: C.sea, alignItems: 'center', justifyContent: 'center', borderTopLeftRadius: 30, borderBottomRightRadius: 30 },
  markText: { color: C.white, fontSize: 32, fontFamily: Platform.select({ android: 'serif', ios: 'Songti SC' }) },
  splashName: { marginTop: 20, color: C.white, fontSize: 28, letterSpacing: 8, fontFamily: Platform.select({ android: 'serif', ios: 'Songti SC' }) },
  splashTag: { marginTop: 10, color: '#89A5A7', fontSize: 12, letterSpacing: 2 },
  library: { flex: 1, backgroundColor: C.ink },
  libraryHeader: { height: 86, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  libraryHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  eyebrow: { color: C.sea, fontSize: 9, letterSpacing: 2.8, fontWeight: '700' },
  libraryTitle: { color: C.white, fontSize: 30, marginTop: 2, letterSpacing: 5, fontFamily: Platform.select({ android: 'serif', ios: 'Songti SC' }) },
  iconButtonDark: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, borderColor: '#385057', alignItems: 'center', justifyContent: 'center' },
  pressed: { opacity: 0.65, transform: [{ scale: 0.97 }] },
  libraryScroll: { paddingHorizontal: 24, paddingTop: 12, paddingBottom: 48 },
  libraryDismissSpacer: { minHeight: 44 },
  cardPressed: { opacity: 0.78, transform: [{ scale: 0.985 }] },
  bookGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'flex-start' },
  sortableGrid: { position: 'relative' },
  sortableDismissLayer: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 },
  bookTileWrap: { width: '46%', marginBottom: 28 },
  sortableTile: { position: 'absolute', marginBottom: 0 },
  bookTile: { width: '100%', aspectRatio: BOOK_COVER_ASPECT_RATIO, backgroundColor: '#35565A', elevation: 4, shadowColor: '#071315', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 8 },
  coverImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  coverFallback: { flex: 1, padding: 16, overflow: 'hidden' },
  coverLine: { height: 1, width: 28, backgroundColor: 'rgba(255,255,255,.65)', marginTop: 5, marginBottom: 20 },
  coverTitle: { color: C.white, fontSize: 20, lineHeight: 28, fontFamily: Platform.select({ android: 'serif', ios: 'Songti SC' }) },
  coverAuthor: { color: 'rgba(255,255,255,.7)', fontSize: 10, marginTop: 10 },
  coverSeal: { position: 'absolute', right: 10, bottom: 11, color: 'rgba(255,255,255,.5)', fontSize: 9, borderWidth: 1, borderColor: 'rgba(255,255,255,.35)', padding: 4 },
  bookProgress: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 3, backgroundColor: 'rgba(0,0,0,.25)' },
  bookProgressFill: { height: 3, backgroundColor: C.seaPale },
  bookOpening: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(10,31,35,.45)', alignItems: 'center', justifyContent: 'center' },
  tileTitle: { color: C.white, fontSize: 13, fontWeight: '600', marginTop: 10 },
  tileAuthor: { color: '#7F9698', fontSize: 10, marginTop: 4 },
  addTileWrap: { width: '46%', marginBottom: 28 },
  addTile: { width: '100%', aspectRatio: BOOK_COVER_ASPECT_RATIO, borderWidth: 1, borderStyle: 'dashed', borderColor: '#466065', alignItems: 'center', justifyContent: 'center' },
  addText: { color: C.seaPale, marginTop: 10, fontSize: 12, fontWeight: '600' },
  addHint: { color: '#687E80', fontSize: 9, marginTop: 5 },
  libraryNotice: { position: 'absolute', left: 0, right: 0, minHeight: 50, flexDirection: 'row', alignItems: 'center', borderTopWidth: StyleSheet.hairlineWidth, paddingHorizontal: 24, paddingTop: 3, paddingBottom: 3 },
  libraryNoticeIcon: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginRight: 9 },
  libraryNoticeText: { flex: 1, fontSize: 11, lineHeight: 16, fontWeight: '700' },
  libraryRemoveAction: { width: 42, height: 42, borderWidth: 1, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
  bookRemovalMarker: { position: 'absolute', top: 8, right: 8, width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  dataPage: { flex: 1, backgroundColor: C.paper },
  dataTop: { height: 62, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line },
  dataTopTitle: { color: C.text, fontSize: 16, fontWeight: '700' },
  dataScroll: { padding: 20, paddingBottom: 46 },
  dataHero: { borderWidth: 1, padding: 18, marginBottom: 12 },
  dataKicker: { fontSize: 9, letterSpacing: 2.2, fontWeight: '800', marginBottom: 15 },
  dataHeroRow: { flexDirection: 'row', alignItems: 'center' },
  dataHeroMark: { width: 48, height: 55, borderTopLeftRadius: 24, borderTopRightRadius: 6, borderBottomRightRadius: 24, borderBottomLeftRadius: 6, alignItems: 'center', justifyContent: 'center' },
  dataHeroCopy: { flex: 1, paddingLeft: 14 },
  dataHeroTitle: { fontFamily: 'serif', fontSize: 25 },
  dataHeroSubtitle: { fontSize: 11, lineHeight: 17, marginTop: 4 },
  dataHeroBody: { fontSize: 11, lineHeight: 18, marginTop: 16 },
  dataStats: { flexDirection: 'row', borderWidth: 1, minHeight: 70, marginBottom: 12 },
  dataStat: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: C.line },
  dataStatValue: { fontSize: 21, fontWeight: '800', fontVariant: ['tabular-nums'] },
  dataStatLabel: { fontSize: 10, marginTop: 3 },
  dataAction: { borderWidth: 1, padding: 15, marginBottom: 10 },
  dataActionTop: { flexDirection: 'row', alignItems: 'flex-start' },
  dataActionIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  dataActionCopy: { flex: 1, paddingLeft: 12, paddingTop: 1 },
  dataActionTitle: { fontSize: 14, fontWeight: '800' },
  dataActionText: { fontSize: 10, lineHeight: 16, marginTop: 5 },
  dataActionButton: { minHeight: 44, borderWidth: 1, alignItems: 'center', justifyContent: 'center', marginTop: 14 },
  dataActionButtonText: { fontSize: 11, fontWeight: '800' },
  dataSecurity: { flexDirection: 'row', borderWidth: 1, padding: 13, marginTop: 2 },
  dataSecurityCopy: { flex: 1, paddingLeft: 10 },
  dataSecurityTitle: { fontSize: 11, fontWeight: '800' },
  dataSecurityText: { fontSize: 10, lineHeight: 16, marginTop: 4 },
  dataNotice: { fontSize: 10, lineHeight: 16, textAlign: 'center', marginTop: 12 },
  dataError: { borderWidth: 1, padding: 11, fontSize: 10, lineHeight: 16, marginTop: 12 },
  dataPreviewHero: { borderWidth: 1, padding: 18, marginBottom: 12 },
  dataPreviewStamp: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginBottom: 15 },
  dataPreviewEyebrow: { fontSize: 9, letterSpacing: 2, fontWeight: '800' },
  dataPreviewFile: { fontSize: 17, fontWeight: '800', marginTop: 8 },
  dataPreviewDate: { fontSize: 10, marginTop: 6 },
  dataPreviewStats: { flexDirection: 'row', borderWidth: 1, minHeight: 70, marginBottom: 12 },
  dataPreviewStat: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: C.line },
  dataPreviewStatValue: { fontSize: 20, fontWeight: '800', fontVariant: ['tabular-nums'] },
  dataPreviewStatLabel: { fontSize: 10, marginTop: 3 },
  dataPreviewList: { borderWidth: 1, paddingHorizontal: 14, paddingVertical: 8, marginBottom: 12 },
  dataPreviewRow: { minHeight: 40, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line },
  dataPreviewRowText: { flex: 1, fontSize: 11, lineHeight: 16, paddingLeft: 9 },
  dataMergeHint: { fontSize: 10, lineHeight: 16, marginBottom: 14 },
  dataPrimaryButton: { minHeight: 46, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  dataPrimaryButtonText: { fontSize: 12, fontWeight: '800' },
  dataSecondaryButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, marginTop: 8 },
  dataSecondaryButtonText: { fontSize: 11, fontWeight: '700' },
  dataComplete: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28 },
  dataCompleteMark: { width: 68, height: 68, borderRadius: 34, alignItems: 'center', justifyContent: 'center' },
  dataCompleteTitle: { fontFamily: 'serif', fontSize: 26, marginTop: 18 },
  dataCompleteText: { fontSize: 12, lineHeight: 20, textAlign: 'center', marginTop: 9 },
  dataCompleteWarning: { fontSize: 10, lineHeight: 16, textAlign: 'center', marginTop: 16 },
  readerRoot: { flex: 1 },
  reader: { flex: 1 },
  readerIcon: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
  readerBottom: { position: 'absolute', zIndex: 20, bottom: 26, left: 14, right: 14, height: 62, borderWidth: StyleSheet.hairlineWidth, borderRadius: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', elevation: 9, shadowColor: '#071315', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.24, shadowRadius: 12 },
  bottomAction: { width: 50, height: 52, alignItems: 'center', justifyContent: 'center', gap: 2 },
  bottomLabel: { fontSize: 11 },
  bottomAa: { fontFamily: 'serif', fontSize: 20, fontWeight: '600', lineHeight: 22 },
  progressPill: { minWidth: 82, alignItems: 'center' },
  progressMain: { fontSize: 16, fontWeight: '700', marginBottom: 2 },
  progressText: { fontSize: 10 },
  liveProgressCard: { position: 'absolute', zIndex: 30, left: 18, right: 18, bottom: 100, borderWidth: StyleSheet.hairlineWidth, borderRadius: 7, paddingHorizontal: 16, paddingTop: 13, paddingBottom: 12, elevation: 11, shadowColor: '#071315', shadowOffset: { width: 0, height: 7 }, shadowOpacity: 0.26, shadowRadius: 14 },
  liveProgressTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  liveProgressLabel: { fontSize: 9, fontWeight: '800', letterSpacing: 1.4 },
  liveProgressPercent: { fontSize: 20, fontWeight: '800' },
  liveProgressChapter: { fontFamily: Platform.select({ android: 'serif', ios: 'Songti SC' }), fontSize: 14, marginTop: -1, marginBottom: 11 },
  liveProgressTrack: { height: 3, overflow: 'hidden' },
  liveProgressFill: { height: 3 },
  searchSheet: { height: '84%', maxHeight: '84%', minHeight: 0, paddingBottom: 0 },
  searchHeaderCopy: { flex: 1 },
  searchInputRow: { height: 48, borderWidth: 1, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12 },
  searchInput: { flex: 1, minWidth: 0, fontSize: 14, paddingVertical: 0, marginLeft: 8 },
  searchClearButton: { width: 34, height: 42, alignItems: 'center', justifyContent: 'center' },
  searchStatusRow: { minHeight: 35, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  searchStatus: { flex: 1, fontSize: 10, lineHeight: 15 },
  searchError: { borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 10, paddingVertical: 8, fontSize: 10, lineHeight: 16, marginBottom: 7 },
  searchList: { flex: 1 },
  searchListContent: { paddingBottom: 26 },
  searchEmptyContent: { flexGrow: 1 },
  searchEmpty: { flex: 1, minHeight: 260, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 26 },
  searchEmptyTitle: { fontSize: 14, fontWeight: '700', marginTop: 11 },
  searchEmptyText: { fontSize: 10, lineHeight: 16, textAlign: 'center', marginTop: 5 },
  searchSectionLabel: { minHeight: 32, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 9 },
  searchSectionText: { flex: 1, fontSize: 10, fontWeight: '800' },
  searchSectionCount: { fontSize: 9 },
  searchResult: { minHeight: 66, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 11 },
  searchExcerpt: { flex: 1, fontFamily: Platform.select({ android: 'serif', ios: 'Songti SC' }), fontSize: 13, lineHeight: 20, paddingRight: 8 },
  searchMatch: { fontWeight: '800' },
  disabledControl: { opacity: 0.45 },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  aiOverlayRoot: { ...StyleSheet.absoluteFillObject, zIndex: 100, elevation: 100 },
  scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(4,18,21,.58)' },
  sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, maxHeight: '82%', minHeight: 350, backgroundColor: '#F3F5F0', borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 22 },
  sheetFillBelow: { position: 'absolute', top: '100%', left: 0, right: 0 },
  handle: { width: 34, height: 4, borderRadius: 2, backgroundColor: '#C2CAC5', alignSelf: 'center', marginTop: 10, marginBottom: 8 },
  sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12 },
  sheetEyebrow: { color: C.sea, fontSize: 9, letterSpacing: 2, fontWeight: '800' },
  sheetTitle: { color: C.text, fontSize: 23, fontFamily: 'serif' },
  closeButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#E4E8E2', alignItems: 'center', justifyContent: 'center' },
  tocList: { marginTop: 3 },
  tocItem: { height: 60, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line, flexDirection: 'row', alignItems: 'center', paddingRight: 8 },
  tocDisclosure: { width: 30, height: 60, alignItems: 'center', justifyContent: 'center' },
  tocDisclosureSpacer: { width: 30, height: 60 },
  tocTitle: { flex: 1, color: C.text, fontFamily: 'serif', fontSize: 15, paddingVertical: 4 },
  currentDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: C.sea },
  bookmarksSheet: { height: '78%', maxHeight: '78%' },
  marginTabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: C.line, marginBottom: 12 },
  marginTab: { flex: 1, height: 39, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  marginTabActive: { borderBottomColor: C.sea },
  marginTabText: { color: C.muted, fontSize: 11 },
  marginTabTextActive: { fontWeight: '800' },
  bookmarkSelectionActions: { position: 'absolute', alignSelf: 'center', bottom: 10, flexDirection: 'row', gap: 8 },
  bookmarkSelectionButton: { minWidth: 52, height: 44, borderWidth: 1, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center', borderRadius: 12, elevation: 8 },
  bookmarkSelectionButtonText: { fontSize: 11, fontWeight: '800' },
  bookmarkActionIconRemove: { backgroundColor: '#F8F1EB' },
  bookmarksList: { paddingBottom: 28 },
  bookmarksEmptyList: { flexGrow: 1 },
  bookmarksEmpty: { flex: 1, minHeight: 260, alignItems: 'center', justifyContent: 'center' },
  bookmarksEmptyTitle: { color: C.text, fontSize: 14, fontWeight: '700', marginTop: 10 },
  bookmarksEmptyText: { color: C.muted, fontSize: 10, marginTop: 5 },
  bookmarkItem: { flexDirection: 'row', paddingVertical: 13, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line },
  bookmarkRail: { width: 18, alignItems: 'center', paddingTop: 5 },
  bookmarkDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.sea },
  bookmarkLine: { width: 1, flex: 1, backgroundColor: '#D5DDD7', marginTop: 5 },
  bookmarkContent: { flex: 1, minWidth: 0, paddingHorizontal: 8 },
  bookmarkChapter: { color: '#397A76', fontSize: 11, fontWeight: '800' },
  bookmarkLocation: { color: '#8A9898', fontSize: 9, marginTop: 3 },
  bookmarkExcerpt: { color: C.text, fontFamily: Platform.select({ android: 'serif', ios: 'Songti SC' }), fontSize: 13, lineHeight: 20, marginTop: 7 },
  bookmarkDelete: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  conversationItem: { minHeight: 126, flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 13, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line },
  conversationTitle: { color: C.text, fontSize: 12, fontWeight: '700', marginTop: 7 },
  conversationExcerpt: { color: C.text, fontFamily: Platform.select({ android: 'sans-serif', ios: 'Helvetica Neue' }), fontSize: 13, lineHeight: 20, marginTop: 7 },
  conversationViewer: { height: '86%', maxHeight: '86%' },
  dragHandleZone: { height: 27, marginHorizontal: -22, alignItems: 'center', justifyContent: 'flex-start' },
  historyHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line },
  historyChapter: { flex: 1, minWidth: 0, color: C.text, fontSize: 14, marginTop: 3 },
  returnButton: { flexShrink: 0, flexDirection: 'row', alignItems: 'center', gap: 4, height: 34, paddingHorizontal: 9, borderWidth: 1, borderColor: '#BCD1CA', borderRadius: 17 },
  returnButtonText: { color: '#397B77', fontSize: 10, fontWeight: '800' },
  historyAnchor: { backgroundColor: '#E4EAE4', borderLeftWidth: 2, borderLeftColor: C.sea, padding: 12, marginTop: 11 },
  historyAnchorLabel: { color: '#397873', fontSize: 9, fontWeight: '800', marginBottom: 5 },
  historyAnchorText: { color: '#526466', fontSize: 12, lineHeight: 19 },
  historyMessages: { paddingTop: 14, paddingBottom: 0 },
  historyScroll: { flex: 1 },
  historyQuestionBlock: { alignSelf: 'flex-end', maxWidth: '88%', backgroundColor: '#DDEBE6', paddingHorizontal: 13, paddingVertical: 10, marginBottom: 11, borderRadius: AI_RADIUS.surface },
  historyFirstQuestionBlock: { marginTop: 16 },
  historyQuestionText: { color: C.text, fontSize: 13, lineHeight: 19 },
  historyAnswerBlock: { paddingVertical: 7, marginBottom: 14 },
  historyLastAnswerBlock: { paddingBottom: 0, marginBottom: 0 },
  latestBottomSpacer: { height: 16 },
  messageTime: { color: C.muted, fontSize: 9, lineHeight: 12, letterSpacing: 0.3, marginTop: 5 },
  answerMessageTime: { marginTop: -6 },
  questionMessageTime: { textAlign: 'right' },
  historyError: { color: '#9A5D42', backgroundColor: '#F4E6DC', fontSize: 10, lineHeight: 16, padding: 10, marginBottom: 10, borderRadius: AI_RADIUS.compact },
  historyComposer: { borderTopWidth: 0, flexDirection: 'column', alignItems: 'stretch', backgroundColor: '#F3F5F0', paddingTop: 8, paddingBottom: 7 },
  typeSheet: { height: '82%', maxHeight: '82%', paddingBottom: 0 },
  typeScroll: { paddingBottom: 34 },
  controlLabel: { color: C.muted, fontSize: 11, marginTop: 15, marginBottom: 8 },
  typePreview: { minHeight: 86, marginTop: 14, paddingHorizontal: 15, paddingVertical: 10, justifyContent: 'center' },
  typePreviewText: { color: C.text, fontFamily: Platform.select({ android: 'serif', ios: 'Songti SC' }), textAlign: 'center' },
  layoutPairRow: { flexDirection: 'row', gap: 10 },
  layoutPairGroup: { flex: 1, minWidth: 0 },
  layoutPairLabel: { marginTop: 0 },
  fontSizeSliderRow: { flexDirection: 'row', marginTop: 15 },
  optionRow: { flexDirection: 'row', gap: 7 },
  inlineSettingRow: { minHeight: 58, marginTop: 15, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: APPEARANCE_RADIUS.card },
  inlineSettingCopy: { flex: 1, paddingRight: 12 },
  inlineSettingTitle: { fontSize: 12, fontWeight: '700' },
  inlineSettingHint: { fontSize: 9, marginTop: 4 },
  inlineSettingControl: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  inlineSettingValue: { fontSize: 10, fontWeight: '700' },
  spacingSliderRow: { flexDirection: 'row', gap: 8 },
  spacingSliderCard: { flex: 1, minHeight: 70, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 10, paddingTop: 9, paddingBottom: 3, borderRadius: APPEARANCE_RADIUS.card },
  spacingSliderHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  spacingSliderLabel: { fontSize: 11, fontWeight: '700' },
  spacingSliderValue: { minWidth: 28, textAlign: 'right', fontSize: 11, fontWeight: '800', fontVariant: ['tabular-nums'] },
  spacingSlider: { width: '100%', height: 36, marginTop: 2 },
  marginGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  marginSliderCard: { width: '48.5%', minHeight: 72, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 10, paddingTop: 9, paddingBottom: 3, borderRadius: APPEARANCE_RADIUS.card },
  marginSliderHead: { flexDirection: 'row', alignItems: 'center' },
  marginDirectionIcon: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  marginDirection: { flex: 1, marginLeft: 7, fontSize: 11, fontWeight: '700' },
  marginValue: { minWidth: 24, textAlign: 'right', fontSize: 11, fontWeight: '800', fontVariant: ['tabular-nums'] },
  marginSlider: { width: '100%', height: 34, marginTop: 1 },
  appearanceOption: { flex: 1, minHeight: 38, borderWidth: 1, borderColor: C.line, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 7, borderRadius: APPEARANCE_RADIUS.option },
  appearanceOptionActive: { borderColor: C.sea, backgroundColor: '#E0ECE8' },
  appearanceOptionText: { color: C.muted, fontSize: 11 },
  appearanceOptionTextActive: { fontWeight: '800' },
  themeRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 7 },
  themeChoice: { flex: 1, borderWidth: 1, borderColor: C.line, padding: 8, alignItems: 'center', borderRadius: APPEARANCE_RADIUS.card },
  themeChoiceActive: { borderColor: C.sea, backgroundColor: '#E7EFEB' },
  themeSwatch: { height: 35, alignSelf: 'stretch', borderWidth: StyleSheet.hairlineWidth, borderColor: '#B9C1BC', borderRadius: APPEARANCE_RADIUS.swatch },
  themeName: { color: C.text, fontSize: 11, marginTop: 7 },
  aiSheet: { minHeight: 0, maxHeight: '82%', borderTopLeftRadius: AI_RADIUS.sheet, borderTopRightRadius: AI_RADIUS.sheet },
  aiSheetInitial: { maxHeight: '72%' },
  aiSheetExpanded: { height: '82%' },
  aiScroll: { flexShrink: 1 },
  aiScrollContent: { paddingBottom: 0 },
  contextCard: { backgroundColor: '#E5EAE4', borderLeftWidth: 2, borderLeftColor: C.sea, padding: 14, marginTop: 10, borderRadius: AI_RADIUS.surface },
  contextLabelRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 7 },
  contextLabel: { color: '#397873', fontSize: 10, fontWeight: '700' },
  contextSummary: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  contextSummaryText: { fontSize: 9 },
  contextText: { color: '#4E6264', fontSize: 13, lineHeight: 21 },
  contextImages: { gap: 8, paddingTop: 10, paddingBottom: 2 },
  contextImagePress: { width: 62, height: 62, borderRadius: AI_RADIUS.image, overflow: 'hidden' },
  contextImage: { width: 62, height: 62, borderWidth: 1, backgroundColor: '#DDE5DF', resizeMode: 'cover', borderRadius: AI_RADIUS.image },
  contextImageIndex: { position: 'absolute', right: 3, bottom: 3, minWidth: 16, height: 16, borderRadius: 8, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3 },
  contextImageIndexText: { color: '#FFFFFF', fontSize: 9, fontWeight: '800' },
  contextNotes: { marginTop: 11, paddingTop: 10, borderTopWidth: StyleSheet.hairlineWidth },
  contextNotesHeader: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  contextNotesHeaderText: { fontSize: 10, fontWeight: '800' },
  contextNotesRail: { gap: 8, paddingTop: 9, paddingBottom: 2 },
  contextNoteCard: { width: 220, height: 76, borderWidth: StyleSheet.hairlineWidth, padding: 10, overflow: 'hidden', borderRadius: AI_RADIUS.compact },
  contextNoteScroll: { flex: 1 },
  contextNoteScrollContent: { paddingHorizontal: 2 },
  contextNoteText: { fontSize: 11, lineHeight: 17 },
  contextRequest: { marginTop: 13, paddingTop: 10, borderTopWidth: StyleSheet.hairlineWidth },
  contextRequestHeader: { minHeight: 30, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  contextRequestTitle: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  contextRequestMeta: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  contextRequestBody: { marginTop: 7, borderWidth: StyleSheet.hairlineWidth, padding: 10, borderRadius: AI_RADIUS.compact },
  contextRequestText: { fontSize: 11, lineHeight: 18 },
  contextControlLabel: { color: C.muted, fontSize: 10, fontWeight: '700', marginTop: 14, marginBottom: 7 },
  contextSliderHead: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 14 },
  contextSliderValue: { fontSize: 11, fontWeight: '800', marginBottom: 7 },
  contextSlider: { width: '100%', height: 36, marginTop: -1 },
  contextSliderMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: -4 },
  contextSliderHint: { fontSize: 9 },
  thinkingComposerToggle: { minHeight: 32, borderWidth: 1, borderRadius: 16, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 4 },
  thinkingComposerToggleText: { fontSize: 10, fontWeight: '700' },
  thinkingTrace: { marginTop: 8, overflow: 'hidden' },
  thinkingTraceHeader: { minHeight: 34, paddingHorizontal: 2, paddingVertical: 5, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  thinkingTraceTitle: { fontSize: 10, fontWeight: '700' },
  thinkingTraceBody: { maxHeight: 190, marginHorizontal: 2, marginBottom: 8, paddingTop: 8 },
  thinkingTraceBodyContent: { paddingBottom: 12 },
  thinkingTraceText: { fontSize: 12, lineHeight: 19 },
  answerCard: { marginTop: 17, backgroundColor: C.white, padding: 18, borderWidth: 1, borderColor: '#D5DDD7', borderRadius: AI_RADIUS.surface },
  answerText: { color: C.text, fontSize: 15, lineHeight: 25 },
  askAgain: { flexDirection: 'row', gap: 5, alignItems: 'center', marginTop: 15 },
  askAgainText: { color: C.sea, fontSize: 11, fontWeight: '700' },
  errorCard: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#F5E8DF', padding: 12, marginTop: 12, borderRadius: AI_RADIUS.compact },
  errorText: { flex: 1, color: '#745543', fontSize: 11, lineHeight: 17 },
  errorLink: { color: '#A35E3D', fontSize: 11, fontWeight: '800' },
  aiComposer: { borderTopWidth: 0, paddingTop: 8, paddingBottom: 5 },
  questionBox: { minHeight: 86, borderWidth: 1, borderColor: '#CAD3CC', backgroundColor: C.white, paddingHorizontal: 8, paddingTop: 3, paddingBottom: 5, marginBottom: 4, borderRadius: AI_RADIUS.field },
  questionInput: { flex: 1, minHeight: 40, maxHeight: 90, color: C.text, fontSize: 13, paddingHorizontal: 5, paddingVertical: 8 },
  questionBoxFooter: { minHeight: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sendButton: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  sendDisabled: { backgroundColor: '#B8C3BF' },
  imagePreviewRoot: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 18 },
  imagePreviewCard: { width: '100%', maxWidth: 520, height: '82%', maxHeight: 476, borderWidth: 1, overflow: 'hidden', borderRadius: 20, elevation: 18, shadowColor: '#071315', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.35, shadowRadius: 22 },
  imagePreviewImage: { width: '100%', flex: 1, minHeight: 0, backgroundColor: '#0A1719' },
  imagePreviewFooter: { minHeight: 56, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingLeft: 16, paddingRight: 10 },
  imagePreviewLabel: { fontSize: 11, fontWeight: '700' },
  settingsPage: { flex: 1, backgroundColor: C.paper },
  settingsTop: { height: 62, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line },
  settingsTopTitle: { color: C.text, fontSize: 16, fontWeight: '700' },
  saveText: { color: '#397F7B', fontSize: 14, fontWeight: '800', width: 42, textAlign: 'center' },
  settingsScroll: { padding: 24, paddingBottom: 50 },
  settingsIntro: { marginBottom: 30 },
  settingsMark: { width: 46, height: 53, borderTopLeftRadius: 23, borderTopRightRadius: 6, borderBottomLeftRadius: 6, borderBottomRightRadius: 23, backgroundColor: C.sea, alignItems: 'center', justifyContent: 'center', marginBottom: 17 },
  settingsIntroTitle: { color: C.text, fontFamily: 'serif', fontSize: 25 },
  settingsIntroText: { color: C.muted, fontSize: 12, lineHeight: 20, marginTop: 9 },
  field: { marginBottom: 18 },
  fieldLabel: { color: C.text, fontSize: 11, fontWeight: '700', marginBottom: 8 },
  fieldInput: { height: 50, backgroundColor: '#F7F8F4', borderWidth: 1, borderColor: C.line, paddingHorizontal: 14, color: C.text, fontSize: 13 },
  fieldInputMultiline: { height: 86, paddingTop: 12, textAlignVertical: 'top' },
});

export const markdownStyles = StyleSheet.create({
  body: { color: C.text, fontSize: 15, lineHeight: 25 },
  paragraph: { marginTop: 0, marginBottom: 11 },
  heading1: { color: C.text, fontSize: 21, lineHeight: 29, marginTop: 8, marginBottom: 11 },
  heading2: { color: C.text, fontSize: 18, lineHeight: 26, marginTop: 8, marginBottom: 9 },
  heading3: { color: C.text, fontSize: 16, lineHeight: 24, fontWeight: '700', marginTop: 6, marginBottom: 7 },
  strong: { color: '#153B3D', fontWeight: '800' },
  em: { color: '#4D6263', fontStyle: 'italic' },
  bullet_list: { marginBottom: 10 },
  ordered_list: { marginBottom: 10 },
  list_item: { marginBottom: 5 },
  bullet_list_icon: { color: C.sea, marginRight: 8 },
  blockquote: { backgroundColor: '#E7ECE6', borderLeftColor: C.sea, borderLeftWidth: 3, paddingHorizontal: 12, paddingVertical: 7, marginVertical: 8, borderRadius: AI_RADIUS.compact },
  code_inline: { color: '#315B5A', backgroundColor: '#E3E9E4', fontFamily: Platform.select({ android: 'monospace', ios: 'Menlo' }), fontSize: 13, paddingHorizontal: 4, borderRadius: 5 },
  fence: { color: '#D8E7E4', backgroundColor: C.ink2, borderColor: C.ink2, fontFamily: Platform.select({ android: 'monospace', ios: 'Menlo' }), fontSize: 12, lineHeight: 19, padding: 12, marginVertical: 8, borderRadius: AI_RADIUS.compact, overflow: 'hidden' },
  link: { color: '#347E79', textDecorationLine: 'underline' },
  hr: { backgroundColor: C.line, height: StyleSheet.hairlineWidth, marginVertical: 14 },
});
