import { rollup } from 'rollup';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const bundle = await rollup({
  input: fileURLToPath(new URL('../web/foliate-entry.js', import.meta.url)),
  plugins: [
    {
      name: 'epub-only',
      resolveId(source) {
        if (source === './pdf.js') return '\0foliate-pdf-disabled';
        return null;
      },
      load(id) {
        if (id === '\0foliate-pdf-disabled') {
          return `export const makePDF = async () => { throw new Error('PDF is not enabled in this EPUB reader') }`;
        }
        return null;
      },
    },
    nodeResolve({ browser: true }),
  ],
});
const { output } = await bundle.generate({
  format: 'iife',
  inlineDynamicImports: true,
  generatedCode: 'es2015',
});
await bundle.close();

const code = output.find((item) => item.type === 'chunk')?.code;
if (!code) throw new Error('Foliate bundle did not produce JavaScript');

const outputDirectory = new URL('../src/generated/', import.meta.url);
await mkdir(outputDirectory, { recursive: true });
await writeFile(
  new URL('foliateBundle.ts', outputDirectory),
  `// Generated by npm run build:foliate. Foliate-js commit is pinned in package.json.\nexport const FOLIATE_BUNDLE = ${JSON.stringify(code)};\n`,
);
