import { rollup } from 'rollup';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const bundle = await rollup({
  input: fileURLToPath(new URL('../web/foliate-entry.js', import.meta.url)),
  plugins: [
    {
      name: 'epub-only',
      resolveId(source) {
        if (source === './pdf.js') return '\0foliate-pdf-disabled';
        return null;
      },
      load(id) {
        if (id === '\0foliate-pdf-disabled') {
          return `export const makePDF = async () => { throw new Error('PDF is not enabled in this EPUB reader') }`;
        }
        return null;
      },
    },
    {
      name: 'mowen-full-page-surface',
      transform(code, id) {
        if (!id.replace(/\\/g, '/').endsWith('foliate-js/paginator.js')) return null;
        const boxedViewport = `#container {
            grid-column: 2 / 5;
            grid-row: 2;
            overflow: hidden;
        }`;
        const fullPageViewport = `#container {
            grid-column: 1 / -1;
            grid-row: 1 / -1;
            overflow: hidden;
        }`;
        const delayedUnlock = `        if (shouldGo || !this.hasAttribute('animated')) await wait(100)`;
        const immediateUnlock = `        if (shouldGo && this.hasAttribute('animated')) await wait(100)`;
        const defaultSelectionPaging = `        const checkPointerSelection = debounce((range, sel) => {
            if (!sel.rangeCount) return
            const selRange = sel.getRangeAt(0)
            const backward = selectionIsBackward(sel)
            if (backward && selRange.compareBoundaryPoints(Range.START_TO_START, range) < 0)
                this.prev()
            else if (!backward && selRange.compareBoundaryPoints(Range.END_TO_END, range) > 0)
                this.next()
        }, 700)`;
        const manualSelectionPaging = `        const checkPointerSelection = () => {}`;
        if (!code.includes(boxedViewport)) {
          throw new Error('Foliate paginator layout changed; update Mowen page-surface patch');
        }
        if (!code.includes(delayedUnlock)) {
          throw new Error('Foliate paginator navigation changed; update Mowen page-turn patch');
        }
        if (!code.includes(defaultSelectionPaging)) {
          throw new Error('Foliate paginator selection changed; update Mowen selection-boundary patch');
        }
        return {
          code: code
            .replace(boxedViewport, fullPageViewport)
            .replace(delayedUnlock, immediateUnlock)
            .replace(defaultSelectionPaging, manualSelectionPaging),
          map: null,
        };
      },
    },
    nodeResolve({ browser: true }),
  ],
});
const { output } = await bundle.generate({
  format: 'iife',
  inlineDynamicImports: true,
  generatedCode: 'es2015',
});
await bundle.close();

const code = output.find((item) => item.type === 'chunk')?.code;
if (!code) throw new Error('Foliate bundle did not produce JavaScript');

const outputDirectory = new URL('../src/generated/', import.meta.url);
await mkdir(outputDirectory, { recursive: true });
await writeFile(
  new URL('foliateBundle.ts', outputDirectory),
  `// Generated by npm run build:foliate. Foliate-js commit is pinned in package.json.\nexport const FOLIATE_BUNDLE = ${JSON.stringify(code)};\n`,
);
